### ISSUE TITLE
String database question

### ISSUE THREAD

**Issue by wfma** [VCCRI/scTalk#3]
Hi guys! Quick question on the string reference. Does it compare my data to all available string annotations? How can I compare only to experimentally validated annotations?

Thanks,
Wei

**Comment by rj-patrick** [comment]
Hi Wei,

Sorry for the slow reply. The starting point is the set of ligand:receptor pairs from Ramilowski et al., which are based on a combination of confirmed ligand:receptor interactions and physically interacting proteins. I add the STRING scores to give a continuous weighting in the graph, but the actual interactions should have been confirmed previously (at least in human). That said, if you are working with mouse and want to only use interactions confirmed in mouse as well, I could feasibly add an option to use interactions confirmed in that species. 

Cheers,
Ralph

**Comment by wfma** [comment]
Thanks Ralph. I am also guilty of slow replies. Thats very helpful! I am only working with human data, but might become helpful for others who are working in mouse? 

Wei

**Comment by rj-patrick** [comment]
Hi Wei,

I've made an update so that the STRING evidence class can be selected when running GenerateEdgeWeights. There is now a variable, string.evidence.class that can be set, for example to ''experiments" or "database". See ?GenerateEdgeWeights for the list of available evidence classes. 

Let me know if you have any issues.

Cheers,
Ralph

**Comment by wfma** [comment]
Amazing. Thank you!
